### ISSUE TITLE
Solutionhub plugins does not work with notepad++ with version 7.6 and up

### ISSUE THREAD

**Issue by grzegorz-wolszczak** [incrediblejr/nppplugins#1]
After upgrading notepad++ from version 7.5.9 to 7.6 (or later) solution plugin menu entries disappeared

I've downloaded plugins from http://www.incrediblejunior.com/npp_plugins/

**Comment by incrediblejr** [comment]
This is because Notepad++ has gone back and forth on the plugin installation folder.

It all started in version [7.6](https://notepad-plus-plus.org/news/notepad-7.6-released.html) and depending on the version you are using be sure to read the [release-notes/news](https://notepad-plus-plus.org/news/) to figure out the current plugin location.
